version: '2'

services:
     mysql_db:
      image: "mysql:5.7"
      container_name: mysql_database
      expose:
       - "3306"
      ports:
       - "3306:3306"
      environment:
       - MYSQL_ROOT_PASSWORD=Hashmap@1
      restart: always
     web:
      build: .
      restart: unless-stopped
      depends_on:
       - "mysql_db"
      command: [ "python", "test.py"]
      #environment:
      # - MYSQL_DATABASE="test"
      # - MYSQL_HOST="mysql_database"
      links: 
       - mysql_db:mysql_db
